"""YOPO RGB-D FULL training with the accepted DEIMv2 YOLO26m backbone."""

_base_ = ["./nocs_fruits_2026_rgbd_shared_stage8_sensor_depth_anchor.py"]

model = dict(
    backbone=dict(
        beta_init=0.0,
        rgb_backbone=dict(
            _delete_=True,
            type="YOLO26MBackbone",
            in_channels=3,
            return_idx=[1, 2, 3],
            init_cfg=None,
        ),
    ),
    neck=dict(in_channels=[512, 512, 512]),
)

# Generated by tools/model_converters/prepare_yolo26m_rgbd_checkpoint.py.
# This is a weight-only initialization, never an optimizer-state resume.
load_from = "work_dirs/yolo26m_rgbd_stage1_initial.pth"
resume = False

work_dir = "work_dirs/yopo_yolo26m_rgbd_stage1_full_20260906"
