"""G10 raw feature initialization for pseudo sequence-context ablations."""

_base_ = ["./nocs_fruits_2026_rgbd_yolo26s_n_sequential_baseline.py"]

sequence_context = dict(
    manifest_path="data/yopo_sequence_640x480/sequence_manifest.json",
    initial_checkpoint="work_dirs/yopo_geometry_depth_shape_20260906/epoch_10.pth",
    work_dir="work_dirs/yopo_sequence_context_corrected_v2_20260907",
    checkpoint_kind="raw",
    annotation_kind="pseudo",
    metric_prefix="proxy_",
    modes=["B0", "B1", "B2", "C0", "C1"],
    seed=20260907,
    feature_extraction=dict(
        source="frozen_g10_backbone_pyramid_obb_center",
        cache_dtype="float16",
        probe_batch_sizes=[
            832,
            800,
            768,
            736,
            704,
            672,
            640,
            576,
            512,
            448,
            384,
            320,
            256,
            192,
            128,
            96,
            64,
            32,
            16,
            8,
            4,
            2,
            1,
        ],
    ),
    association=dict(max_distance_m=0.075, ambiguity_margin_m=0.003),
    pairs=dict(min_train_matches=2, min_eval_matches=0),
    head=dict(embedding_dim=128, hidden_dim=256, context_radius_m=0.15),
    optimizer=dict(
        type="yopo.engine.optimizers.amuse.AmuseOptimizer",
        lr=5e-4,
        aux_lr=5e-4,
        weight_decay=1e-4,
        warmup_steps=100,
    ),
    training=dict(epochs=20, patience=5, pair_batch_size=32),
    evaluation=dict(
        embedding_gate=0.50,
        comparison_contract="B0/B1/B2/C0/C1_same_seed_same_candidates_v1",
        requires_independently_checked_correspondence_for_adoption=True,
    ),
    inference=dict(
        detector_precision="float32",
        score_threshold=0.30,
        max_detections=128,
        tracker=dict(
            geometry_gate_m=0.075,
            embedding_gate=0.50,
            geometry_weight=0.50,
            embedding_weight=0.50,
            miss_cost=0.55,
            new_cost=0.55,
            min_confirmed_hits=2,
            max_unobserved_frames=2,
            prototype_update_confidence=0.70,
            prototype_momentum=0.90,
        ),
    ),
)
