_base_ = ['./nocs_yopo_real_camera_r50_rgbd.py']

# Custom RGB-D (single-class fruit) dataset on the NOCS "real" layout.
# data_root contains real/train_list.txt, real/test_list.txt, scene_1_train/,
# scene_1_val/ (color + depth + train-style label pkl), generated by
# scripts/gen_yopo_ds.py from the WildDet3D custom RGB-D data.
dataset_type = 'NOCSDataset'
data_root = 'data/nocs_custom/'

# Camera intrinsics of the custom capture (single shared K across all frames),
# overriding the stock NOCS/REAL275 hard-coded values.
custom_intrinsic = [443.9066, 449.1953, 321.3503, 230.8687]

model = dict(
    bbox_head=dict(
        type='DINO9DCenter2DPoseHead',
        num_classes=1,  # single class: fruit
        classwise_rotation=True,
        classwise_sizes=True))

# ── Pipelines (RGB-D 4-channel) ───────────────────────────────────────────
backend_args = None
scale = (640, 480)
train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadDepthImageFromFile', backend_args=backend_args,
         to_float32=True),
    dict(type='Load9DPoseAnnotations', with_bbox=True,
         with_centers_2d=True, with_z=True),
    dict(type='ConcatDepthToImage'),
    dict(type='Resize', scale=scale, keep_ratio=True),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomTranslatePixels', prob=0.5, max_translate_offset=50),
    dict(type='RandomFlipFor9DPose', prob=0.5),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
    dict(type='Pack9DPoseInputs'),
]

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadDepthImageFromFile', backend_args=backend_args,
         to_float32=True),
    dict(type='Load9DPoseAnnotations', with_bbox=True,
         with_centers_2d=True, with_z=True),
    dict(type='ConcatDepthToImage'),
    dict(type='Resize', scale=scale, keep_ratio=True),
    dict(
        type='Pack9DPoseInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'intrinsic', 'models_info_path'),
    ),
]

train_dataloader = dict(
    _delete_=True,
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        split='real_train',
        intrinsic=custom_intrinsic,
        pipeline=train_pipeline,
        backend_args=backend_args))

# Disable val/test for the initial smoke run: the val layout (train-style
# label pkl under scene_1_val/, no segmentation_results/) differs from the
# NOCS real_test split expectations. Keep all three (dataloader/cfg/evaluator)
# None together to satisfy mmengine's all-None-or-all-set rule.
val_dataloader = None
val_cfg = None
val_evaluator = None
test_dataloader = None
test_cfg = None
test_evaluator = None

max_epochs = 1
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=max_epochs)
