[project]
name = "yopo-clone"
version = "0.1.0"
requires-python = ">=3.8, <3.9"
dependencies = [
    "muon-optimizer",
    "schedulefree==1.4.1",
    "torch==2.4.0",
]

[tool.uv.sources]
muon-optimizer = { git = "https://github.com/KellerJordan/Muon.git", rev = "f98f1cacc0263b04290753e32be8d498c1efc806" }

[tool.uv]
package = false
