"""Smoke inference script for the YOPO DINO9DCenter2DPose model.

Loads one synthetic frame from a NOCSDataset test split, runs a forward
pass through the model, and prints the shapes / keys of the predictions.

Usage (from the YOPO repo root):
    python scripts/smoke_infer.py \\
        --data data/nocs_smoke \\
        --config configs/yopo/nocs_yopo_real_camera_r50.py \\
        --ckpt work_dirs/smoke_nocs_r50_1iter/epoch_1.pth \\
        --device cuda:0

If --ckpt is omitted or the path does not exist the model runs with random
weights (a warning is printed).

Dependencies:
    All YOPO runtime deps (torch, mmcv, mmengine, yopo package itself).
    The synthetic data is generated by:
        python scripts/gen_synthetic_nocs.py --out data/nocs_smoke --n 4
"""

import argparse
import os
import sys
import warnings

import torch


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--config",
        default="configs/yopo/nocs_yopo_real_camera_r50.py",
        help="Path to the mmengine config file (default: "
             "configs/yopo/nocs_yopo_real_camera_r50.py)",
    )
    p.add_argument(
        "--ckpt",
        default=None,
        help="Path to a checkpoint (.pth). If absent, random init is used.",
    )
    p.add_argument(
        "--data",
        default="data/nocs_smoke",
        help="Root of the synthetic dataset (default: data/nocs_smoke)",
    )
    p.add_argument(
        "--device",
        default="cuda:0",
        help="Device string (default: cuda:0).  Use 'cpu' for CPU-only runs.",
    )
    return p.parse_args()


def build_model_from_cfg(cfg):
    """Build the YOPO model from an mmengine Config object.

    The config's model dict is passed to MODELS.build(), which resolves
    the 'type' key to the registered class (DINO9DCenter2DPose).
    The data_preprocessor is embedded inside the model dict and gets
    built automatically by the base class __init__.
    """
    from mmengine.registry import init_default_scope
    init_default_scope('yopo')
    from yopo.registry import MODELS  # noqa: F401  (ensure registrations are loaded)

    model = MODELS.build(cfg.model)
    return model


def load_one_test_sample(cfg, data_root: str):
    """Run the test pipeline on the first frame of the real_test split.

    Returns:
        dict with 'inputs' (Tensor CHW) and 'data_samples' (DetDataSample).
    """
    from yopo.registry import DATASETS

    # Override data_root so the dataset points to synthetic data
    dataset_cfg = dict(
        type='NOCSDataset',
        data_root=data_root,
        split='real_test',
        test_mode=True,
        pipeline=cfg.test_pipeline,
    )
    dataset = DATASETS.build(dataset_cfg)

    if len(dataset) == 0:
        raise RuntimeError(
            f"Dataset at '{data_root}' has 0 samples for split 'real_test'. "
            "Run scripts/gen_synthetic_nocs.py first."
        )

    # Use the first sample; dataset.__getitem__ runs the full pipeline.
    sample = dataset[0]
    return sample


def print_prediction_summary(predictions) -> None:
    """Print type, shape, and keys for each prediction in the list."""
    print("\n--- Prediction summary ---")
    for i, pred in enumerate(predictions):
        print(f"  sample[{i}]: {type(pred).__name__}")
        if hasattr(pred, "pred_instances"):
            pi = pred.pred_instances
            print(f"    pred_instances keys: {list(pi.keys())}")
            for k in pi.keys():
                v = pi[k]
                if hasattr(v, "shape"):
                    print(f"      {k}: shape={v.shape} dtype={v.dtype}")
                else:
                    print(f"      {k}: {type(v)}")
        else:
            print("    (no pred_instances attribute)")
    print("--------------------------")


def main() -> None:
    args = parse_args()

    # ── 1. Load config ────────────────────────────────────────────────────────
    from mmengine.config import Config

    if not os.path.isfile(args.config):
        sys.exit(f"Config not found: {args.config}")

    cfg = Config.fromfile(args.config)
    print(f"Config loaded: {args.config}")

    # ── 2. Import YOPO to trigger all module registrations ────────────────────
    # This must happen before any MODELS / TRANSFORMS lookup.
    import yopo  # noqa

    # ── 3. Build model ────────────────────────────────────────────────────────
    # cfg.model is a ConfigDict; MODELS.build resolves type='DINO9DCenter2DPose'
    # and recursively builds sub-modules (backbone, neck, bbox_head, etc.)
    # including the data_preprocessor (DetDataPreprocessor).
    model = build_model_from_cfg(cfg)
    print(f"Model built: {type(model).__name__}")

    # ── 4. Load checkpoint (optional) ─────────────────────────────────────────
    if args.ckpt and os.path.isfile(args.ckpt):
        from mmengine.runner import load_checkpoint
        load_checkpoint(model, args.ckpt, map_location="cpu")
        print(f"Checkpoint loaded: {args.ckpt}")
    else:
        if args.ckpt:
            warnings.warn(
                f"Checkpoint not found at '{args.ckpt}'. "
                "Running with random/pretrained-backbone weights.",
                UserWarning,
            )
        else:
            warnings.warn(
                "No --ckpt provided. Running with random/pretrained-backbone weights.",
                UserWarning,
            )

    # ── 5. Move model to device ───────────────────────────────────────────────
    device = torch.device(args.device)
    model.to(device)
    model.eval()
    print(f"Model on device: {device}")

    # ── 6. Load one test sample ───────────────────────────────────────────────
    # The dataset + pipeline produce a dict with keys:
    #   'inputs'       : Tensor (C, H, W)
    #   'data_samples' : DetDataSample
    print(f"Loading test sample from: {args.data}")
    sample = load_one_test_sample(cfg, args.data)

    # ── 7. Build a minimal batch ──────────────────────────────────────────────
    # model.test_step / model.predict expect:
    #   data = dict(inputs=Tensor (B,C,H,W), data_samples=List[DetDataSample])
    # DetDataPreprocessor inside the model normalises inputs and pads the
    # batch to a common size, so we can pass a single-element batch.
    inputs = sample["inputs"].unsqueeze(0).to(device)   # (1, C, H, W)
    data_samples = [sample["data_samples"]]             # List[DetDataSample]

    # Move data_sample metainfo to device is handled internally by the model.
    data = dict(inputs=inputs, data_samples=data_samples)

    # ── 8. Forward pass ───────────────────────────────────────────────────────
    # model.predict is the test-time entry point in mmdetection 3.x:
    #   1. data_preprocessor normalises pixel values and handles batching.
    #   2. backbone + neck extract multi-scale features.
    #   3. DINO transformer encoder + decoder runs.
    #   4. bbox_head decodes detections into (bboxes, scores, labels,
    #      translations, rotations, sizes, T).
    # Results land in data_sample.pred_instances.
    print("Running forward pass (eval + no_grad)...")
    with torch.no_grad():
        # test_step calls data_preprocessor then predict; it is the cleanest
        # public API for a single test batch in mmengine-style detectors.
        predictions = model.test_step(data)

    print("Forward pass completed.")

    # ── 9. Inspect predictions ────────────────────────────────────────────────
    print_prediction_summary(predictions)

    # Quick sanity: pred_instances should have the keys expected by NOCSMetric
    required_keys = {"bboxes", "scores", "labels", "translations",
                     "rotations", "sizes", "T"}
    if hasattr(predictions[0], "pred_instances"):
        pred_keys = set(predictions[0].pred_instances.keys())
        missing = required_keys - pred_keys
        if missing:
            warnings.warn(
                f"pred_instances is missing expected keys: {missing}",
                UserWarning,
            )
        else:
            print(f"All required prediction keys present: {sorted(required_keys)}")
    else:
        warnings.warn("predictions[0] has no pred_instances!", UserWarning)

    print("\nSMOKE INFER OK")


if __name__ == "__main__":
    main()
